name: Terraform Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    name: Deploy Infrastructure to LocalStack
    runs-on: ubuntu-latest
    
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,ec2
          DEBUG: 1
        options: >-
          --health-cmd "awslocal s3 ls || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0
    
    - name: Configure AWS CLI for LocalStack
      run: |
        aws configure set aws_access_key_id test
        aws configure set aws_secret_access_key test
        aws configure set region us-east-1
    
    - name: Wait for LocalStack
      run: |
        echo "Waiting for LocalStack to be ready..."
        sleep 10
        curl -s http://localhost:4566/_localstack/health
    
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./infrastructure
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ./infrastructure
      continue-on-error: false
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color
      working-directory: ./infrastructure
    
    - name: Verify Resources
      run: |
        echo "Verificando recursos creados en LocalStack..."
        aws s3 ls --endpoint-url=http://localhost:4566
    
    - name: Show Terraform State
      run: terraform show
      working-directory: ./infrastructure
