name: Terraform Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0
    
    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true
      working-directory: ./infrastructure
    
    - name: Terraform Init
      id: init
      run: terraform init -backend=false
      working-directory: ./infrastructure
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./infrastructure
    
    - name: Comment PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const output = `#### Terraform Format: \`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization: \`${{ steps.init.outcome }}\`
          #### Terraform Validation: \`${{ steps.validate.outcome }}\`
          
          *Pushed by: @${{ github.actor }}*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
